[Global]
AppName = "ginadmin"
Version = "0.1.0"
Debug = true

[Global.Http]
Addr = ":8848"
ShutdownTimeout = 10
ReadTimeout = 60
WriteTimeout = 60
IdleTimeout = 10
SSLCertFile = ""
SSLKeyFile = ""

[Util]

[Util.Prometheus]
Enable = false
Port = 9100
BasicUsername = "admin"
BasicPassword = "admin"
LogApis = []
LogMethods = []
DefaultCollect = true